### PR TITLE
Added translations to /ru/_legacy/administering-your-site/

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
Added translations:
ru\_legacy\administering-your-site\customizing-the-manager-via-plugins.md
ru\_legacy\administering-your-site\fc-resource.md

### CODE REVIEW

**Comment by Mark-H** [comment]
If you want to translate what's in the `_legacy` directory that's of course up to you, but the reason they are in that directory is because I don't think those pages serve a purpose anymore. There may b  other pages on the same topic that are more up-to-date, or they only served as an index page before.

**Comment by Ruslan-Aleev** [comment]
So, I did not know about it :)
It is somehow necessary to indicate that there were no mistake.
In other sections there are links to it /_legacy/, is it a mistake or not?

**Comment by Mark-H** [comment]
Anything that links to `/_legacy/` should be fixed. If it makes it easier, I could remove `_legacy` completely so we don't get the confusion?

**Comment by Ruslan-Aleev** [comment]
Yes, in my opinion, it is better to delete unnecessary folders.

**Comment by Mark-H** [comment]
I've removed _legacy so think this can be closed?

**Pull request closed without merging**
