### PR TITLE
Link fix after the reorganization

### PR DESCRIPTION
**Pull request by Ibochkarev**
## Description of improvements

After the reorganization a lot of links was to issue a 404 error. This PR fixes some links in those documents, which are translated into the Russian language.

In the future, you need to write a script to fix the links is not a redirect. I am in process of translation into Russian will rule in the original and in translations.

### CODE REVIEW

**Comment by Mark-H** [comment]
Are you sure they caused a 404? 

Earlier this week I updated the app to look for redirects when rendering the content, so that it would automatically update links, and make broken links red to make them easier to spot: https://github.com/Mark-H/DocsApp/commit/498386ffeed32a34428f883b896a54d9165a885e#diff-cfc3dd585e11840583070e0be8e410c9 

When I look at a sample of the links you've changed, they all do seem to be properly redirected. Or am I misunderstanding something or just looking wrong?

Of course, yes, old links still need to be fixed in the source, so thank you for taking the time to do that.

**Comment by Ibochkarev** [comment]
Maybe I used the wrong word. 
But I fixed all the links on a page using https://github.com/Mark-H/Docs/blob/2.x/redirects.json

I think it will not hurt =)

**Comment by Mark-H** [comment]
👍

**Comment by Ibochkarev** [comment]
Index  MODX Documentation 2019-03-16 04-37-55
It's really cool! Thank you!

**Pull request merged**
