### PR TITLE
broken links fixed

### PR DESCRIPTION
**Pull request by ant-tar**
## Description

SOme setting links have been fixed

## Affected versions

 2.x, 3.x

## Relevant issues

#34

### CODE REVIEW

**Review by Ibochkarev — APPROVED** [review]

**Comment by ant-tar** [comment]
@Ibochkarev don't know why, but for some reason, last pages exist
https://docs.modx.com/current/en/building-sites/settings/log_level
https://docs.modx.com/current/en/building-sites/settings/log_target etc.
but have "Last updated not available " and left menu doesn't show them at all...
Please advise what's wrong

**Comment by Ibochkarev** [comment]
> @Ibochkarev don't know why, but for some reason, last pages exist
> https://docs.modx.com/current/en/building-sites/settings/log_level
> https://docs.modx.com/current/en/building-sites/settings/log_target etc.
> but have "Last updated not available " and left menu doesn't show them at all...
> Please advise what's wrong
> 

@Mark-H Please see what the problem is. I looked - I did not understand why this is so

**Comment by Mark-H** [comment]
Looks like it may not work on the first time a file is added for some reason, it showed up on log_level after another edit.

**Comment by ant-tar** [comment]
> 
> 
> Looks like it may not work on the first time a file is added for some reason, it showed up on log_level after another edit.

Hi @Mark-H, I've uploaded new RU translations, and situation is the same unfortunately :( , I don't see new settings in left menu(please see cache_alias_map)

)

**Pull request merged**
