### PR TITLE
move MIGXdb Tutorials from MIGX folder to MIGXdb folder

### PR DESCRIPTION
**Pull request by Bruno17**
## Description

moves MIGXdb Tutorials from MIGX folder to MIGXdb folder.
This tutorials belong to MIGXdb stuff.

## Affected versions

the change is relevant to both. 
Changes for MODX3 will follow.

## Relevant issues

Please link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by Mark-H** [comment]
Should probably put in place some redirects for this, see redirects.json in the root.

Also no need to create a second pr for 3.x, every now and then I'll merge those up.

**Comment by Bruno17** [comment]
I've added two redirects. Not sure, what is wrong with the json now.
Also, do I need to add slashes at the beginning of the old url?

**Comment by Bruno17** [comment]
> Also no need to create a second pr for 3.x, every now and then I'll merge those up.

not sure, how that works, but then I will wait, before I add 3.x relevant stuff to that files.

**Comment by Bruno17** [comment]
> I've added two redirects. Not sure, what is wrong with the json now. Also, do I need to add slashes at the beginning of the old url?

ok, the missing slashes was the issue

**Review by Ibochkarev — APPROVED** [review]

**Comment by Bruno17** [comment]
@Mark-H @Ibochkarev 
the redirects doesn't seem to work. 
https://docs.modx.org/current/en/extras/migx/migx.tutorials/creating-cmp
while this would work:
https://docs.modx.org/en/extras/migx/migx.tutorials/creating-cmp
I think, I have to add the /current part to the old url???

**Pull request merged**
